### ISSUE TITLE
There is no "message" element for key extName. 

### ISSUE THREAD

**Issue by jingyuli811** [vladikoff/chromeos-apk#110]
The latest chromeos-apk 4.0.0 generates _locales\en\messages.json with contents looking like

{
  "appNotSupported": {
    "description": "Message displayed when the app is not supported.",
    "message": "This app is incompatible with your device. Check to make sure other Android apps work for you from the Chrome Web Store"
  },
  "extName": {
    "description": "Extension name",
  }
}

This differs from what 3.0.0 had generated, which looks like
{
  "appNotSupported": {
    "description": "Message displayed when the app is not supported.",
    "message": "This app is incompatible with your device. Check to make sure other Android apps work for you from the Chrome Web Store"
  },
  "extName": {
    "description": "Extension name",
    "message": "com.rovio.angrybirdsrio"
  }
}

The difference is that extName entry does not have "message" defined, which causes error when runing the App. The error  says: There is no "message" element for key extName.

**Comment by roablep** [comment]
I also had the exact same issue with a different app and `ARChon Custom Runtime 1.2 - x86_64 38.4410.120.43`. My solution was what @vizshala had implemented.
