### ISSUE TITLE
Unrecognized manifest key 'arc_metadata'.

### ISSUE THREAD

**Issue by nickwales** [vladikoff/chromeos-apk#117]
I'm getting the above having tried to install skype. 

I created the package on ubuntu 14.04, had the issue with extName not having a message section, and am now struggling with the above. The app installs, but has the android logo and launches with nothing but a box with the android logo.

**Comment by Polytronic** [comment]
I've waited for it to work for over 10 minutes now, and nothing. The only thing that I can find wrong is the arc_metadata. I'm using a Samsung Series 3 Chromebook, if that helps.

**Comment by volfin** [comment]
if it takes 5 minutes it sounds like the emulator is bad. shouldn't be so slow.
