### ISSUE TITLE
vladikoff-archon-xxxxxx disapears when I reload

### ISSUE THREAD

**Issue by mvaneijgen** [vladikoff/chromeos-apk#12]
When I "load unpacked extension..." in Version 39.0.2163.3 of canary it works fine, but as soon as I reload it disappears.

![disconnect anchor](https://cloud.githubusercontent.com/assets/3217544/4344769/8916aa68-40a4-11e4-972f-2f2d973d99bb.gif)

Mac OS X 10.9.3

**Comment by nanoeray** [comment]
what is the solution? i have same issue
