### ISSUE TITLE
Error: failed to fetch from registry: chromeos-apk

### ISSUE THREAD

**Issue by fabmin** [vladikoff/chromeos-apk#150]
Trying to install chromeos-apk via npm, getting the following:

(precise)@localhost:~$ sudo npm install chromeos-apk -g
npm http GET https://registry.npmjs.org/chromeos-apk

npm ERR! Error: failed to fetch from registry: chromeos-apk

npm ERR!     at /usr/share/npm/lib/utils/npm-registry-client/get.js:139:12
npm ERR!     at cb (/usr/share/npm/lib/utils/npm-registry-client/request.js:31:9)
npm ERR!     at Request._callback (/usr/share/npm/lib/utils/npm-registry-client/request.js:136:18)
npm ERR!     at Request.callback (/usr/lib/nodejs/request/main.js:119:22)
npm ERR!     at Request.<anonymous> (/usr/lib/nodejs/request/main.js:212:58)
npm ERR!     at Request.emit (events.js:88:20)
npm ERR!     at ClientRequest.<anonymous> (/usr/lib/nodejs/request/main.js:412:12)
npm ERR!     at ClientRequest.emit (events.js:67:17)
npm ERR!     at HTTPParser.onIncoming (http.js:1261:11)
npm ERR!     at HTTPParser.onHeadersComplete (http.js:102:31)
npm ERR! You may report this log at:
npm ERR!     <http://bugs.debian.org/npm>
npm ERR! or use
npm ERR!     reportbug --attach /home/robuntu/npm-debug.log npm
npm ERR! 
npm ERR! System Linux 3.8.11
npm ERR! command "node" "/usr/bin/npm" "install" "chromeos-apk" "-g"
npm ERR! cwd /home/robuntu
npm ERR! node -v v0.6.12
npm ERR! npm -v 1.1.4
npm ERR! message failed to fetch from registry: chromeos-apk
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/robuntu/npm-debug.log
npm not ok
(precise)robuntu@localhost:~$ sudo npm install chromeos-apk -g
npm http GET https://registry.npmjs.org/chromeos-apk

npm ERR! Error: failed to fetch from registry: chromeos-apk
npm ERR!     at /usr/share/npm/lib/utils/npm-registry-client/get.js:139:12
npm ERR!     at cb (/usr/share/npm/lib/utils/npm-registry-client/request.js:31:9)
npm ERR!     at Request._callback (/usr/share/npm/lib/utils/npm-registry-client/request.js:136:18)
npm ERR!     at Request.callback (/usr/lib/nodejs/request/main.js:119:22)
npm ERR!     at Request.<anonymous> (/usr/lib/nodejs/request/main.js:212:58)
npm ERR!     at Request.emit (events.js:88:20)
npm ERR!     at ClientRequest.<anonymous> (/usr/lib/nodejs/request/main.js:412:12)
npm ERR!     at ClientRequest.emit (events.js:67:17)
npm ERR!     at HTTPParser.onIncoming (http.js:1261:11)
npm ERR!     at HTTPParser.onHeadersComplete (http.js:102:31)
npm ERR! You may report this log at:
npm ERR!     <http://bugs.debian.org/npm>
npm ERR! or use
npm ERR!     reportbug --attach /home/robuntu/npm-debug.log npm
npm ERR! 
npm ERR! System Linux 3.8.11
npm ERR! command "node" "/usr/bin/npm" "install" "chromeos-apk" "-g"
npm ERR! cwd /home/robuntu
npm ERR! node -v v0.6.12
npm ERR! npm -v 1.1.4
npm ERR! message failed to fetch from registry: chromeos-apk
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/robuntu/npm-debug.log
npm not ok

**Comment by vladikoff** [comment]
Update node.js, npm ERR! node -v v0.6.12 is really old

**Comment by iorch** [comment]
@vladikoff I have the same problem. I'm a noob with node and chromeOS, how do you update node.js?

**Comment by vladikoff** [comment]
@iorch hey, it is different on every operating system, I suggest you google that.

You might find it easier to use other tools that convert APKs: see https://archon-runtime.github.io/ Software / Utilities section
