### ISSUE TITLE
Failed to load extension...'import" extension is not installed.

### ISSUE THREAD

**Issue by eaugust** [vladikoff/chromeos-apk#151]
Failed to load extension from: ~/chromeos-apk-master/APKs/com.alphonso.pulse/com.alphonso.pulse.android
'import' extension is not installed.

Here's the manifest.json file contents:

{
  "app": {
    "background": {
      "page": "app_main.html"
    }
  },
  "arc_metadata": {
    "apkList": [
      "custom-android-release-1400197.apk"
    ],
    "enableExternalDirectory": false,
    "formFactor": "phone",
    "name": "com.alphonso.pulse",
    "orientation": "portrait",
    "packageName": "com.alphonso.pulse",
    "useGoogleContactsSyncAdapter": false,
    "usePlayServices": [
      "gcm"
    ]
  },
  "default_locale": "en",
  "icons": {
    "16": "icon.png",
    "128": "icon.png"
  },
  "import": [
    {
      "id": "mfaihdlpglflfgpfjcifdjdjcckigekc"
    }
  ],
  "manifest_version": 2,
  "name": "__MSG_extName__",
  "oauth2": {
    "client_id": "133701689125-jj0hr4gb0ff4ulsbrn0uk2i4th946d4c.apps.googleusercontent.com",
    "scopes": []
  },
  "offline_enabled": true,
  "permissions": [
    "gcm",
    {
      "socket": [
        "tcp-connect",
        "tcp-listen",
        "udp-bind",
        "udp-send-to",
        "resolve-host"
      ]
    },
    "unlimitedStorage",
    "notifications",
    "clipboardRead",
    {
      "fileSystem": [
        "write"
      ]
    },
    "https://clients2.google.com/",
    "videoCapture",
    "clipboardWrite",
    "identity.email",
    "alarms",
    "storage",
    "identity",
    "audioCapture"
  ],
  "requirements": {
    "3D": {
      "features": [
        "webgl"
      ]
    }
  },
  "update_url": "https://localhost",
  "version": "1337"
}

**Comment by vladikoff** [comment]
Did you add ARChon or Google's Runtime (if on a Chromebook)? http://archon-runtime.github.io/

**Comment by eaugust** [comment]
Yes (if it matters, I'm running Ubuntu 14.04)
![chrome extensions](https://cloud.githubusercontent.com/assets/10822498/6013803/a68d5a72-ab27-11e4-8b73-8dd691c30052.png)

**Comment by vladikoff** [comment]
ID should say `ID: mfaihdlpglflfgpfjcifdjdjcckigekc`. Can you try 2.1 -x86_32 from http://archon-runtime.github.io/?

**Comment by eaugust** [comment]
Thanks, I will give it a try and let you know if it works.

**Comment by eaugust** [comment]
Awesome - it worked! Thanks again!

**Comment by LJMJr** [comment]
I'm following the instructions on 
https://www.linux.com/learn/tutorials/842630-installing-android-apps-on-linux-with-archon.
Developer Mode checked
Have loaded: ARChon Custom Runtime 1.2 - x86_32 38.4410.120.43
2 Error messages
'minimum_chrome_version' is only allowed for extensions, hosted apps, legacy packaged apps, and packaged apps, but this is a shared module.
Unrecognized manifest key 'arc_build_tag'.
line 1 to 6 of error page shown below:
  "update_url": "http://localhost",
  "name": "ARChon Custom Runtime 1.2 - x86_32",
  "manifest_version": 2,
  "minimum_chrome_version": "32",
  "version": "38.4410.120.43",
  
I'm using Google Chrome	48.0.2564.10 (Official Build) dev (32-bit).
Ubuntu v12.04 32 bit

I tried to download v2.1 32 bit but when I loaded unpacked extensions it showed as 64 bit, so I stayed with the above.

If I try to load unpacked extensions of an arkchon packaged file I get the following error message:
Failed to load extension from: ~/Cribbage
WebGL is not supported.


Any suggestions?

**Comment by asprakash** [comment]
I am also facing the same issue like LJMJr faced. I am getting the error,  WebGL is not supported.
I am using v2.1 32bit version on Ubuntu 14.04 and my chrome browser version is 48.0.2564.116

**Comment by codywohlers** [comment]
@asprakash you can enable WebGL in `chrome://flags`

**Comment by edmundlaugasson** [comment]
Tried with enabled WebGL and Override... but did not work....

**Comment by Lostguestsneeze** [comment]
Did You Try Updating Your Browser In Your UNBUTU Computer

**Comment by edmundlaugasson** [comment]
Using Arch-based distro, which has usually up-to-date software. Also in current case, the browser was very latest.
