### ISSUE TITLE
No "message" element for key extName.

### ISSUE THREAD

**Issue by picwellwisher12pk** [vladikoff/chromeos-apk#174]
I was trying to install Instagram according to the tutorial and I got this. So far I could not succeed in installing a single android app . 

I am on Ubuntu 14.04 64bit machine.

Failed to load extension from: ~/apks/com.instagram.android.android
There is no "message" element for key extName.

**Comment by picwellwisher12pk** [comment]
Done , thanks

**Comment by alihesari** [comment]
How to solved this problem?
