### ISSUE TITLE
Possibility of Archon as standalone and not as extension - Need help

### ISSUE THREAD

**Issue by madanagopalt** [vladikoff/chromeos-apk#190]
It is nice to see the design of ARChon for chrome browsers. I have a doubt. Since ARC is designed with NACL support (.nexe file) and chrome browser has already support for NACL, we can make archon as standalone html file right?. Also, is it possible to design as standalone application?. Could you please clarify on this.

**Comment by rocketinventor** [comment]
Only for browsers that support portable native client.
It wouldn't be useful anyways because it is just a runtime environment so
it would have to be packaged with the app.
Also, there is a significant amount of files needed.

On Thu, Jul 2, 2015, 12:58 PM madanagopalt <notifications@github.com> wrote:

> It is nice to see the design of ARChon for chrome browsers. I have a
> doubt. Since ARC is designed with NACL support (.nexe file) and chrome
> browser has already support for NACL, we can make archon as standalone html
> file right?. Also, is it possible to design as standalone application?.
> Could you please clarify on this.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vladikoff/chromeos-apk/issues/190>.
>
-- 
Elliot Gerchak,
Owner of dementedLab.com

**Comment by madanagopalt** [comment]
Thanks. So, it is possible right to run as standalone application, even it is not useful?. Please clarify.

**Comment by rocketinventor** [comment]
No, not really.
Archon is not a standalone interface, just a runtime environment. It is
basically just a code interpreter.
The archon runtime does not have an interface of its own and is likely not
configured in a way that is compatible with any webrowsers outside of being
a chrome extension so it would require a lot of reconfiguration to make it
work and it wouldn't do anything, anyways.
Hope that helps.

On Thu, Jul 2, 2015, 8:34 PM madanagopalt <notifications@github.com> wrote:

> Thanks. So, it is possible right to run as standalone application, even it
> is not useful?. Please clarify.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vladikoff/chromeos-apk/issues/190#issuecomment-118202477>
> .
>
-- 
Elliot Gerchak,
Owner of dementedLab.com

**Comment by madanagopalt** [comment]
Thanks. Yes, understood. Archon is providing runtime support from chrome browser to speak with ARC libraries via NACL with it's own set of messages defined. Is it right?.

My understanding from archon is, chrome extension is used for some tasks like taking  input from user (say an example mentioning in manifest file) and some alarm events. Am i right?. 

The configuration changes will be needed to remove those extension invocation. Is it right?. And i accept, it will be having lot of changes to support this as you told.

**Comment by rocketinventor** [comment]
More or less except that chrome extensions can do almost anything that can
be accomplished with HTML5, C (native client), and chrome's API's.
Also, the remainder of the code is likely not capable of being run outside
of a chrome nativeclient context.

On Fri, Jul 3, 2015 at 12:41 AM madanagopalt <notifications@github.com>
wrote:

> Thanks. Yes, understood. Archon is providing runtime support from chrome
> browser to speak with ARC libraries via NACL with it's own set of messages
> defined. Is it right?.
>
> My understanding from archon is, chrome extension is used for some tasks
> like taking input from user (say an example mentioning in manifest file)
> and some alarm events. Am i right?.
>
> The configuration changes will be needed to remove those extension
> invocation. Is it right?. And i accept, it will be having lot of changes to
> support this as you told.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vladikoff/chromeos-apk/issues/190#issuecomment-118229830>
> .
>
-- 
Elliot Gerchak,
Owner of dementedLab.com

**Comment by madanagopalt** [comment]
Thanks Elliot. Yes,as you told remainder of code(i.e HTML,CSS, JAVASCRIPT, NACL ) can't run outside the chrome native client context, since it is being written to utilize chrome NACL support.

As per the details mentioned by you, i understood that it is feasible to make it run as standalone, without extension support, but comes with lot of work. Am i right?. 

What you mean as chrome API's?. Do you mean default chrome browser namespaces available to javascript to perform some functionality that are not part of extensions?.Please clarify.

**Comment by madanagopalt** [comment]
Hi,

Also, we have the nacl nexe arc_nacl_x86_64 right?. Is the code is open source (shared) or not open source. Please clarify. Thanks.

Regards,
Madan

**Comment by rocketinventor** [comment]
By chrome API's, I mean API's that are not available to normal websites but, can be utilized by chrome apps/extensions (sometimes requiring a declared permission).
For example, on ChromeOS, there is a Chrome API to set the wallpaper.

I am not 100% sure on the source code for archon, you might want to contact @vladikoff . You might also, want to take a look at https://en.wikipedia.org/wiki/Google_App_Runtime_for_Chrome, It should clear up some of your confusion. Also, note that archon doesn't seem to be using _portable_ native client, so, unless you compile it to native client, it won't run without being a chrome app (for security reasons).

**Comment by madanagopalt** [comment]
Thanks much for the clarification.

**Comment by rocketinventor** [comment]
You're very welcome!
