### ISSUE TITLE
"There is no "message" element for key extName." error

### ISSUE THREAD

**Issue by FolPo666** [vladikoff/chromeos-apk#244]
Whenever I load the extensions, it gives me this error
![screenshot_1](https://user-images.githubusercontent.com/29904091/27844396-da438ebe-60e6-11e7-9d2d-e3b6a2a2f3ab.png)

Please help!

**Comment by ilyaigpetrov** [comment]
Open `com.your.apk.android/_locales/en/messages.json` and add:
```json
  "extName": {
    "message": "FOOBAR",
    "description": "Extension name"
  }
```
Instead of FOOBAR you may input any name of your choice.

**Comment by mahdi-ln** [comment]
Why you closed this issue. the program still have this problem (version 4.0.2)
