### ISSUE TITLE
minimum_chrome_version' is only allowed for extensions, legacy packaged apps, hosted apps, packaged apps, and themes, but this is a shared module.

### ISSUE THREAD

**Issue by im-nazmul** [vladikoff/chromeos-apk#297]
Hi, 
I downloaded ARChon Custom Runtime 1.2 from given link and while I try to install I got two error.
1. **'minimum_chrome_version' is only allowed for extensions, legacy packaged apps, hosted apps, packaged apps, and themes, but this is a shared module.**
```
{
  "update_url": "http://localhost",
  "name": "ARChon Custom Runtime 1.2 - x86_64",
  "manifest_version": 2,
  "minimum_chrome_version": "32",
  "version": "38.4410.120.43",
  "default_locale": "en",
  "arc_build_tag": "arc-runtime-38.4410.120.43",
  "about_page": "NOTICE.html",
  "key": "MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCwTjmSbBD9uFJEUR7jMYAL1sPXqCNe7ljIb6dheKIYjkNtLt1YuiAw4Pul/PO+aYtm8tsbFnsNZ73AxhMX9aPxuzwlAak/iN6atxv7h8mwOg6HiHdxTDnOPrCv7fEud5aUFaq7sqDhiqwMpJoIOa1w7c299z3oXIrG1FGEkid1IQIDAQAB",
  "export": {
    "resources": [
      "*"
    ]
  },
  "icons": {
    "16": "icon.png",
    "128": "icon.png"
  },
  "platforms": [
    {
      "nacl_arch": "x86-32",
      "sub_package_path": "_platform_specific/nacl_i686/"
    },
    {
      "nacl_arch": "x86-64",
      "sub_package_path": "_platform_specific/nacl_x86_64/"
    },
    {
      "nacl_arch": "arm",
      "sub_package_path": "_platform_specific/bare_metal_arm/"
    }
  ]
}
```
2. **Unrecognized manifest key 'arc_build_tag'.**

```
"manifest_version": 2,
  "minimum_chrome_version": "32",
  "version": "38.4410.120.43",
  "default_locale": "en",
  "arc_build_tag": "arc-runtime-38.4410.120.43",
  "about_page": "NOTICE.html",
  "key": "MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCwTjmSbBD9uFJEUR7jMYAL1sPXqCNe7ljIb6dheKIYjkNtLt1YuiAw4Pul/PO+aYtm8tsbFnsNZ73AxhMX9aPxuzwlAak/iN6atxv7h8mwOg6HiHdxTDnOPrCv7fEud5aUFaq7sqDhiqwMpJoIOa1w7c299z3oXIrG1FGEkid1IQIDAQAB",
  "export": {
    "resources": [
      "*"
    ]
  },
  "icons": {
    "16": "icon.png",
    "128": "icon.png"
  },
  "platforms": [
    {
      "nacl_arch": "x86-32",
      "sub_package_path": "_platform_specific/nacl_i686/"
    },
    {
      "nacl_arch": "x86-64",
      "sub_package_path": "_platform_specific/nacl_x86_64/"
    },
    {
      "nacl_arch": "arm",
      "sub_package_path": "_platform_specific/bare_metal_arm/"
    }
  ]
}
```

Now what can I do for it?

> Note: My Chrome Version is: Version 89.0.4389.82 (Official Build) (64-bit)

Thank you
_Nazmul Hossain_

**Comment by DineshGuptaa** [comment]
Same issue faced but found solution[https://github.com/vladikoff/chromeos-apk/issues/255](https://github.com/vladikoff/chromeos-apk/issues/255). After that I am unable to see icon of the app in chrome://apps. Please help me to launch the app
1.
![image](https://user-images.githubusercontent.com/23373711/110232870-6db5c780-7f46-11eb-95dd-cfaf68302a83.png)

2.
![image](https://user-images.githubusercontent.com/23373711/110232884-8de58680-7f46-11eb-9a44-26d65a1ac9bb.png)

**Comment by im-nazmul** [comment]
I found a solution hope it's work. Open `manifest.json` and these line. Here version will be your chrome version.

```
"manifest_version": 2,
"version": "41.4410.238.0",
"default_locale": "en",
"about_page": "NOTICE.html",
```

**Comment by im-nazmul** [comment]
Sorry for the previous comment. I didn't read well. Sorry. 

> You Just need to re-load this package then you will get it. 

Thank you

**Comment by im-nazmul** [comment]
Another word. This error wont effect on your app either. so don't worry!

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/49443405/110874142-2f395780-830e-11eb-9c97-2b9e6918baff.png)
got same issue here, 
can not install the extension manually.

**Comment by im-nazmul** [comment]
Like i already said this error won't affect in your installed app. You can now start use your emulator.  
But there's an big issue is most of app not working with this emulator anymore. You had better you an emulator app. 
Thanks

**Comment by anikde** [comment]
whenver I try to reload the package, the package vanishes from the extension list. What can be done?

**Comment by beeeater-bit** [comment]
> whenver I try to reload the package, the package vanishes from the extension list. What can be done?

I'm having the exact same issue.

**Comment by marco-github-uk** [comment]
I have he same issue

**Comment by muelxy** [comment]
Have you tried removing the "minimum_chrome_version" key from the manifest.json? Try to remove that and also the 'arc_build_tag' key

**Comment by luiwashere** [comment]
i got 2 errors "minimum_chrome_version" and "arc_build_tag"
removing 
"minimum_chrome_version",
and 
"arc_build_tag": "arc-runtime-41.4410.238.0",

from manifest.json worked for me
