### ISSUE TITLE
Just - Doesn't Loads

### ISSUE THREAD

**Issue by sudo-nautilus** [vladikoff/chromeos-apk#301]
when I launch my app it gets stuck on the screen showing an Android Bot Icon

**Comment by sudo-nautilus** [comment]
Dead issue xd

**Comment by 0rubin** [comment]
wait i had the same problem did you fix it?

**Comment by sudo-nautilus** [comment]
sadly no,
Anyway, https://github.com/vladikoff/chromeos-apk/issues/305#issuecomment-968318150 should help you (I guess). You may emulate Android if you're trying to run .apk files on a desktop with WayDroid or something...
