### ISSUE TITLE
freeze in these image

### ISSUE THREAD

**Issue by mmm286** [vladikoff/chromeos-apk#37]
Hi,
I'm trying to load the example application (uberspot 2048) and it freezes in the screen with android logo.
I have architecture 32bits in my windows. These could be the problem?
Thanks and sorry for my english!

**Comment by illtellyoulater** [comment]
ARChon developers should explicitly state that ARChon is no longer working/supported/maintained!

There's not a single mention of this in hundreds of ARChon official github threads. 
I wasted about 8 full hours trying to make this thing work, being deceived by the their complete lack of communication and the confusion generated by recent posts of other people like me populating these threads in search of answers...

This should be universally considered as the perfect example of how to wrongly manage the discontinuation of a project.
