### ISSUE TITLE
Unable to load unpacked extension

### ISSUE THREAD

**Issue by jaredmcateer** [vladikoff/chromeos-apk#6]
Chrome: Version 38.0.2125.66 beta (64-bit)
OS: Ubuntu 14.04 

I followed the instructions in the read me and I get the following warnings when loading the unpacked extension:

> There were warnings when trying to install this extension:
> - 'minimum_chrome_version' is only allowed for extensions, hosted apps, legacy packaged apps, and packaged apps, but this is a shared module.
> - Unrecognized manifest key 'arc_build_tag'.

It is in my extensions list, however, there is no "Launch" option

**Comment by buntudude** [comment]
This seems like a really old thread, but just a shot - i had the same errors, and even added the unpacked extension for the app i wanted to install, it's still not working. it just loads the GUI icon when I try to launch the app.

**Comment by DavidStojko** [comment]
Same as @buntudude
