### ISSUE TITLE
32 bit support

### ISSUE THREAD

**Issue by JacobShipley** [vladikoff/chromeos-apk#8]
I haven't had the time to take a deep look at the ARChon project yet, but I noticed that the current build does not include 32 bit libraries.

So why does this matter?  While one might think this is a non-factor in the modern world of 64 bit CPUs, it's worth mentioning that millions of tablets and convertible laptops sold within the last year based on Intel's Bay Trail architecture were shipped with 32 bit Windows 8(.1), and a 32 bit UEFI.

**Comment by needshelp947** [comment]
i need help because it keeps going just standing on the loading screen but when i try to remove key from manifest there isnt "such thing"in the manifest.json
