### ISSUE TITLE
Unrecognized manifest key "arc_metadata"

### ISSUE THREAD

**Issue by tleunen** [vladikoff/chromeos-apk#80]
When I load a modified apk with chromeos-apk, there is the warning `Unrecognized manifest key "arc_metadata"` during the installation of the extension on my chromebook.

I'm using Chrome 37.

**Comment by trivikrama619** [comment]
Any updates here ? I have the same above problem (mhohai comment). On Ubuntu 14.04 (64-bit), it gives " unrecognized manifest key 'arc_metadata' " error and the app stays idle at the launch screen (with android image).

**Comment by trivikrama619** [comment]
In error log it shows " timeout to spawn ChildPlugin process: dexopt(so_executable), dexopt --preopt /vendor/chromium/crx/custom-android-release-1400197.apk " and the screen remains idle at launch screen (not responsive). Its surprising that the same thing works on chrome but not on chromium.

**Comment by dbkaynor** [comment]
Report an issue
Google Chrome Version 54.0.2840.100 (64-bit) Linux Mint 
Linux doug-Satellite-L775 4.4.0-47-generic #68-Ubuntu SMP Wed Oct 26 19:39:52 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
gives " unrecognized manifest key 'arc_metadata' " error and the app stays idle at the launch screen (with android image).

Any idea what might be wrong?

**Comment by msdobrescu** [comment]
> Report an issue
> Google Chrome Version 54.0.2840.100 (64-bit) Linux Mint
> Linux doug-Satellite-L775 4.4.0-47-generic #68-Ubuntu SMP Wed Oct 26 19:39:52 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
> gives " unrecognized manifest key 'arc_metadata' " error and the app stays idle at the launch screen (with android image).
> 
> Any idea what might be wrong?

The same here, Sabayon Linux 64 bit.
